version: 2.1
jobs:
  test-and-build:
    docker:
      - image: cimg/base:current
    resource_class: substream/core-runner
    steps:
      - run: npm run test
      - run: npm run build
workflows:
  build-workflow:
    jobs:
      - test-and-build
